### ISSUE TITLE
Data Not Written to Reports + Segfaults

### ISSUE THREAD

**Issue by ArmandB** [IslamAAli/SLAM-DSChar#1]
Hello, 
Thanks for the great work!
Ran it out of the box using the docker instructions and this is kind of how that went:

Unless the report filepath exists, the analysis data isn't written to the reports. Something like adding the line in kitti_min.sh to the other scripts fixed it and allowed the reports to be generated: mkdir ../out_data/reports/KITTI

Characterization option failure:
[g] (general) just immediately segfaults for me
[b] (inertial diff) segfaults
^I don't know what to attribute this to except some issue in the docker build...I remember seeing some red text in the docker build but don't remember what it was

[3] (brightness) gets to 99% for the first input then segfaults...maybe some aggregation or file writing error?
[a] (inertial dynamic range) segfaults with a floating point exception...maybe a divide by 0? Not sure.
^Will probably try and meander my way through these errors in the next couple of weeks.

Thought I'd bring up the part about the reports ASAP and the rest is in case it's useful somehow.

My system is ubuntu 20.04 and docker version is: Docker version 20.10.21, build baeda1f. The dataset I've been working with is euroc

**Comment by IslamAAli** [comment]
Hello, 
Thanks a lot for your feedback .. I think having a lot of people trying to run this code and use it is the way to get it better. 

For the issues you have right here, I wanted to .. did you mount KITTI dataset to the right directory inside the docker image? 

Also, did you change the path in this file to KITTI location? in_data/you_ds_config_file.txt

**Comment by ArmandB** [comment]
For sure!

I believe the dataset was mounted correctly. I changed the in_data/you_ds_config_file.txt file path for euroc to where I have the raw data in the docker environment, and I also changed the euroc.sh script to create the reports/EURO_C/ directory, so the directory used to open the ofstream would exist.
I was able to run all of the analyses except the ones listed to completion, and generated the reports for them. I haven't delved deeply into the results yet, so I'm not sure how well the ones that finished ran, but no errors/segfaults.

Just at a glance, some of them (i.e. blur) look like the results make sense while others are just a text file with:
x y
0 1

Tht could be the correct result. I've just got to check more thoroughly.

**Comment by IslamAAli** [comment]
Thanks for the update.
Some of the metric are done on the sequence level, so, the characterization will be a single value. For example, how many pictures are blurred in the sequence. 
Please refer to our IROS paper for more informaiton. 
https://arxiv.org/abs/2202.11312

Can you tell me which options didn't work with you?

**Comment by ArmandB** [comment]
"Some of the metric are done on the sequence level, so, the characterization will be a single value. For example, how many pictures are blurred in the sequence."
Got it. That makes sense b/c I was only using euroc MH04 to test.

"Can you tell me which options didn't work with you?"
- the ones that didn't work for me are in my first post under: "Characterization option failure"

Did some debugging and figured out at least part of the issue. In the <dataset>_config.txt files (Euroc in my case), there are references to /timestamps.txt and /inertial_data.txt which aren't distributed with the datasets and that I needed to generate using a python script. Still running everything so I don't completely know what works and what doesn't, but the [g] option previously segfaulted and now is working. 

For posterity, here's my python script although git doesn't like the .py extension so I changed it to a .txt
[create_timestamps.txt](https://github.com/IslamAAli/SLAM-DSChar/files/10233035/create_timestamps.txt)

**Comment by IslamAAli** [comment]
Hello again, 

So, I uploaded the script i used for extracting the timestamps and the inertial information and it is now available in:
https://github.com/IslamAAli/SLAM-DSChar/blob/main/ext_tools/Dataset_timestamp_tools.py

please make sure to change the path in the main function of this script to your dataset folder.
