### ISSUE TITLE
Disparity Parameters + Normalization

### ISSUE THREAD

**Issue by ArmandB** [IslamAAli/SLAM-DSChar#2]
The paper says that "The framework uses the default values of the configuration parameters of any underlying engines such as feature extraction, disparity calculations", but the disparity parameters (i.e. for SGBM) seem to be manually set and different than the opencv default:
            -32,    // MinDisparity
        	144,    // NumDisparities
            9,      // block size
            60,     // P1
            2400,   // P2
            90,     // Disp12MaxDiff
            16,     // PreFilterCap
            1,      // UniquenessRatio
            60,     // SpeckleWindowSize
            20,     // SpeckleRange
            true    // SGBM mode
are these from an example somewhere, and if not, how did you arrive at these parameters?

Additionally, the disparity output seems to be normalized w/ NORM_MINMAX before the statistics are collected. Unless the min/max pixel values are always 0,255 will this not degrade the value of comparing the disparity mean and stddev across frames within an input or across input sequences?

**Comment by IslamAAli** [comment]
Yes, the framework use default parameters for underlying engines. The reason for that is how researchers use such engines in their SLAM pipelines. We needed to follow that in SGBM as well and we found out that almost all SLAM systems we experimented used custome parameters. For that, we used the parameter mix we have here which is adopted from ORB-SLAM (I hope I am not mistaken).

For the normalization, we examined for this condition for 4 different datasets (KITTI, TUM-VI, EuroC MAV, and most recently TUM RGB-D). We found out that min is 0 and max is 255, which makes the results consistent for the timebeing . However, you are correct that this case doesn't generalize and needs handling.
